:eclipse_help_center: https://wiki.eclipse.org/Platform/InfoCenter
:blog: https://www.bsi-software.com/scout/toc-xml-from-existing-html/
:wikitext: https://wiki.eclipse.org/Mylyn/WikiText
:issues: https://github.com/jmini/geneclipsetoc/issues
:license: http://www.eclipse.org/legal/epl-v10.html

= geneclipsetoc

Maven plugin to generate an eclipse help toc.xml file from existing html files.

== Description

This is a maven plugin that takes as input an ordered list of HTML pages and that generate a table of content file (`toc.xml` file) for these pages.
With this xml file, it is possible to publish the HTML pages as Guide in an link:{eclipse_help_center}[Eclipse Help Center].

The approach was originally described here: link:{blog}[Generating Eclipse Help from existing HTML Documentation]

It is based on the link:{wikitext}[mylyn-wikitext] framework and very similar to the `wikitext-to-eclipse-help` task provided by the framework.
The only difference here is that there is no markup to HTML conversion during the process.

== Usage

Check out the link:examples/[examples].

== Code

The source code of the plugin is available in the link:code/[code] folder.

=== Build

Run maven install on the corresponding pom file:

  cd code/geneclipsetoc-maven-plugin/
  mvn install

== Get in touch

Use the link:{issues}[geneclipsetoc issue tracker] on GitHub.

== License

link:{license}[Eclipse Public License - v 1.0]
