:eclipse_help_center: https://wiki.eclipse.org/Platform/InfoCenter
:blog: https://www.bsi-software.com/en/scout-blog/article/generating-eclipse-help-from-existing-html-documentation.html
:wikitext: https://wiki.eclipse.org/Mylyn/WikiText
:bug478466: https://bugs.eclipse.org/bugs/show_bug.cgi?id=478466
:issues: https://github.com/jmini/geneclipsetoc/issues
:license: http://www.eclipse.org/legal/epl-v10.html

= geneclipsetoc-maven-plugin

Maven plugin to generate an eclipse help `toc.xml` file from existing html files.

== Description

This is a maven plugin that takes as input an ordered list of HTML pages and that generate a table of content file (`toc.xml` file) for these pages.
With this xml file, it is possible to publish the HTML pages as guide in an link:{eclipse_help_center}[Eclipse Help Center].

The approach was originally described here: link:{blog}[Generating Eclipse Help from existing HTML Documentation]

It is based on the link:{wikitext}[mylyn-wikitext] project and very similar to the `wikitext-to-eclipse-help` task provided by the project.
The only difference here is that there is no markup to HTML conversion during the process.

If you think that `geneclipsetoc` should be contributed to the mylyn-wikitext project, please give your opinion on link:{bug478466}[Bug 478466].

== Usage

Check out the link:examples/[examples].

== Code

As for any maven plugin, the source code of the plugin is available in the link:src/[src] folder.

With Eclipse IDE, here is how you can import this project:

* Clone or add this repository using the "Git Repositories" view.
* Start the "Import Projects..." wizard on the "Working Directory" folder and pick the option "Import as general project".
* Back in the Package Explorer view, select "Configure" > "Convert to Maven Project" on the project.

=== Build

Run maven install on the root pom file:

  mvn install

== Get in touch

Use the link:{issues}[geneclipsetoc issue tracker] on GitHub.

== License

link:{license}[Eclipse Public License - v 1.0]
